spring.application.name=Ohfifthlane_back
#mybatis mapper location 설정
mybatis.mapper-locations=classpath:mapper/mapper-*.xml

#underscore => camel-case
mybatis.configuration.map-underscore-to-camel-case=true

# PostgreSQL 데이터베이스 설정
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/ohfifthlane
spring.datasource.username=postgres
spring.datasource.password=postgis