spring.application.name=Ohfifthlane_back
#mybatis mapper location 설정
mybatis.mapper-locations=classpath:mapper/mapper-*.xml

#underscore => camel-case
mybatis.configuration.map-underscore-to-camel-case=true

# PostgreSQL 데이터베이스 설정
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/team03
spring.datasource.username=postgres
spring.datasource.password=postgis

# Naver API
naver.client-id=di2yQ7AfAwmPIaD_aMFd
naver.secret=_pGT4Uv1MU

# 이미지 저장 경로
#upload.dir=./src/main/resources/static/upload/
upload.dir=../Ohfifthlane_front/src/assets/images/uploads/

# 이메일 인증번호 전송
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lkk030400@gmail.com
spring.mail.password=fufm iybi wshh vpsg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.starttls.enable=true